### ISSUE TITLE
Mod Organizer 2 generic issues

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#304]
I'm planning to add Mod Organizer 2 support.
No idea how good it works, but it looks like that it does work meanwhile without any additional dotnet installation
(so mono seems to be enough). I might be wrong, as I haven't tested much yet.

autodownload and auto installation into an own compatdata and using a seperately configurable proton/wine version does already work. the installed program seems to work basically.

Haven't used MO2 so far, so I need to examine first, how to best implement it seamlessly, but I guess some parts might be similar with what was required for Vortex.

As usual, unexpected help is welcome.

**Comment by frostworx** [comment]
Almost everything works fully automated with zero-config ootb already _(see wip wiki below)_,
but actually using the enabled mods in the game "does not work" yet:
Just guessing, but
it looks like MO2 usvfs is **required**, which kind of overlayfs-es the enabled mods into the game dir.
This would be a no-go for my current implementation, as it would mean _(at least I think so)_
that MO2 needs to be running for the mods to become available in the game or - even worse - the game even needs to be started via MO2.
Additionally, usvfs also [seems to have problems](https://github.com/ModOrganizer2/modorganizer/issues/372) via wine/proton,
which would mean that MO2 would forcefullly require a dotnet installation, which is a problem because since some time there are multiple dotnet wine regression problems, which still don't seem to be fixed - at least with the wine versions used in proton _( same problem with the [Vortex implementation](https://github.com/frostworx/steamtinkerlaunch/wiki/Vortex))_

edit: MO2 itself _(without usvfs)_ seems to work fine with mono _(apart from some minor? warnings)_, so of course it would be nice to  not depend on dotnet48.

If those assumptions are correct, the only _sane_ solution to fix/workaround this, is to hook in an automatic symlinker function, which symlinks the enabled mods into the game before the actual game start _(ands removed disabled ones)_
This might work, but it would be nice, if someone with some knowledge about MO2 could give me some hints how MO2 works here.
edit: removed wip wiki, as it is [online](https://github.com/frostworx/steamtinkerlaunch/wiki/Mod-Organizer-2)

**Comment by frostworx** [comment]
The best way to go would probably be some overlay fs (like overlayfs), but I do not want to use root/sudo or pull in sshfs-overlayfs.
So the only way to go is creating symlinks from the MO2 mod subdir in to the game installation _(and create real directories if they do not exist yet)_.

A game launch with MO2 enabled will kind of look like this:

0) open requester with timeout if MO2 should be opened
  Yes -> continue with 1)
  No -> continue with 4)
  Timeout ->  continue with 4)
1) remove all symlinks pointing into the mod subdir
2) start MO2 for the started game _(if an unsupported game is used, skip to 4)_
3) when MO2 was closed create the symlinks for all enabled mods
4) continue with starting the game _(with symlink-enabled mods, if any)_

**Comment by frostworx** [comment]
A friendly MO2 dev gave me several hints.
I'll cancel the symlink idea, which would probably break too much.
I'll leave above functions in the code though and disable MO2 until usvfs works via wine/proton
and make MO2 start optionally silently to apply the enabled mods.

TL;DR: MO2 support will be ready when USVFS works via proton/wine again (https://github.com/ModOrganizer2/modorganizer/issues/372)

**Comment by frostworx** [comment]
update: `USVFS` **does** work _(used Proton-6.15-GE-2 while testing)_
and even better: 
I also successfully started a game via steam through stl through MO2 silently _(so seamless start into the game, but with MO2 mods enabled using usvfs)_

Some more cleanups, parameters, documentation and the MO2 implementation seems to be pretty much feature complete

**Comment by frostworx** [comment]
The wiki is already up. Feel free to improve it :)
https://github.com/frostworx/steamtinkerlaunch/wiki/Mod-Organizer-2

The code is not 100% ready yet. I hope I find the time to finish it before my **Prague** trip next week _(I love that city!)_ :)

**Comment by desmond27** [comment]
>It is the successor of the Vortex Mod Manager

Actually it's the other way around. Vortex is a successor to Nexus Mod Manager (now defunct). NMM and MO2 existed simultaneously and now since Vortex has replaced NMM, it and MO2 now exist simultaneously.

**Comment by frostworx** [comment]
Oh of course, thanks for heads up...

**Comment by frostworx** [comment]
currently, the main remaining problems are:
- nxm mime-type download function needs to be improved a bit. It basically works, but only when MO2 was started in its own compatdata. It should work as well when started via game launch (so when running in the game compatdata).
- "silent" mode (so loading enabled mods via MO2 silently, without opening its gui) "$randomly" has problems - MO2 complains about "not saving lists during directory update" then and doesn't load the mods. Haven't found a valid workaround yet _(unfortunately, already tried a lot)_

I will be on a 1 week trip starting from tomorrow **\o/**, so I'm afraid a commit won't happen before :(

**Comment by frostworx** [comment]
I tried pretty much everything what came into my mind, but I'm running out of ideas how the silent mode can be fixed...

After the trip I'll improve the mime-type download stuff if possible and consider committing the MO2 feature with the half broken silent mode, in the hope that some people help to find a proper solution.
What do you think?

**Comment by desmond27** [comment]
I don't think silent mode is really necessary since anybody who uses MO2 is already used to using the GUI. I think just getting MO2 to launch using the games prefix from within steam is more important.

**Comment by frostworx** [comment]
I agree that the regular gui mode is more important, but silent mode would be good to have f.e. for VR games,
because the game just starts with mods being applied without needing a click by the user before _(who might already wear the hmd and therefore does not even see the gui waiting for the click)_

**Comment by frostworx** [comment]
**Mod Organizer 2 landed**

I spontaneously decided to commit the [Mod-Organizer 2](https://github.com/frostworx/steamtinkerlaunch/wiki/Mod-Organizer-2) implementation before **Praha**

Most things should work fine, but I'm sure there are several parts which could be improved, so PRs and bug reports welcome!
_(edit: haven't tested much modding functionality yet though, but basically it does work)_

The two major known "problems" remaining:
- **mod download mime-type:**
  The nxm mime type downloader might behave strange, depending on how MO2 was started.
  It seems to work stable though, when starting MO2 regularly _(~~either~~ via game launch ~~or standalone should not matter~~)_
  and then start the browser from the MO2 gui itself (the browser should be closed in the initial launch - funny side effect: The Steam overlay is in the browser then)

- **silent mode:**
  Starting the game with MO2 applying the mods silently still is kind of broken.
  The mods is started _(through MO2)_ but the mods are not applied "randomly".
  In that case the MO2 logs always show this warning: `not saving lists during directory update`
  I tried much but nothing helped.
  
The main initial MO2 commit can be found https://github.com/frostworx/steamtinkerlaunch/commit/78703dc671fc58cd20bbbf9f6bfea153ef6daad5

This follow up commit https://github.com/frostworx/steamtinkerlaunch/commit/2c8813ae739d5e51b4dd050ece80e4c36c941833 disables the silent mode and uses the gui instead, just in case someone wants to play with it :)

**Comment by desmond27** [comment]
Reporting this bug here since you have asked me to do so.

When I try to run stl mo2 s I get the following error:

```
[deathmetal27@soulengine ~]$ stl mo2 s
ln: failed to create symbolic link '/home/deathmetal27/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/ModOrganizer': File exists
ln: failed to create symbolic link '/home/deathmetal27/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/ModOrganizer': File exists
ln: failed to create symbolic link '/home/deathmetal27/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/ModOrganizer': File exists
ln: failed to create symbolic link '/home/deathmetal27/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/ModOrganizer': File exists
Friday 10 September 2021 11:44:55 PM IST INFO - startMO2 - Starting '/home/deathmetal27/.config/stl/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe' in standalone mode
/usr/bin/stl: line 10283: cd: /home/deathmetal27/.config/stl/mo2/compatdata/pfx/drive_c/Modding/MO2: No such file or directory
[deathmetal27@soulengine ~]$
```

I tried this after running stil for Fallout 4 in Steam and I saw the notifications about installing MO2. I see the same notifications when running `stl mo2 s` but I think since it's already installed when running stl from Steam, it's somehow interfering when running from the terminal.

**Comment by frostworx** [comment]
thanks for reporting @desmond27. Just pushed 2 little fixes, which do not fix the core problem completely, but at last catch and log them.
*now leaving home* :)

**Comment by Septimius-Severus** [comment]
Really grateful that I found this when I did, I was actually going to try and make my own (probably inferior) solution when I stumbled across this. I've been having an issue where MO2 won't actually start SKSE64 when I try to boot it from there, and I'm unsure where to look to see if its a bug with stl's implementation or with MO2 itself.

**Comment by desmond27** [comment]
Ok, I installed the latest version of the steamtinkerlaunch-git package from the AUR and ran `stl mo2 s`. This time I get the following error:

```
[deathmetal27@soulengine ~]$ stl mo2 s
Monday 13 September 2021 01:37:37 AM IST SKIP - startMO2 - Could not find '/home/deathmetal27/.config/stl/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe' - can't start ModOrganizer - this should not happen
```

I went into that path and indeed there is no directory named `Modding` in the prefix.

I tried running `stl mo2 i` as well but the behaviour is the same.

**Comment by frostworx** [comment]
Thanks for testing, @desmond27!
Apparently it is a bad idea to make some last minute _fixes_, barely test them and release them for testing before a short trip...
I can confirm that the MO2 installation is broken and will hopefully fix this shortly.

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/commit/4f0208f92a8892d70219edd44d7859c227ac0d68 should fix the mess

**Comment by desmond27** [comment]
The issue still seems to persist:

```
[desmond@soulengine ~]$ stl mo2 s
grep: /mnt/j-drive/SteamLibrary/steamapps/compatdata/1091500/pfx/system.reg: No such file or directory
Tuesday 21 September 2021 04:42:46 AM IST SKIP - startMO2 - Could not find '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe' - can't start ModOrganizer - this should not happen
[desmond@soulengine ~]$
```

I reinstalled steamtinkerlaunch-git from the AUR and ran `stl mo2 s`. The issue appears to be the same, there is no directory named 'Modding' in the prefix. Should I try deleting this prefix and running `stl mo2 s` again?

**Comment by frostworx** [comment]
The "Modding" directory is created by the MO2 installer, so apparently the installer didn't work on your system.
The grep you pasted is strange. Does that wineprefix even exist?

It would be the best if you
- remove/rename the whole `~/.config/stl/`directory
- start `stl mo2 s` again
- and attach the `/dev/shm/stl/stl.log` if it still doesn't work on your system.

**Comment by desmond27** [comment]
Yes, the prefix exists, just that there is no 'Modding' directory under 'drive_c'.

I'll try this out later today and post my findings here.

**Comment by frostworx** [comment]
Strange to see a pfx without a system.reg then.
Either way I added a little check for the system.reg before grepping in it.

**Comment by desmond27** [comment]
Perhaps the prefix is messed up. I'll do what you said: clear it and reinstall MO2.

**Comment by desmond27** [comment]
Ok, so I did what you said.

I deleted `~/.config/stl` and ran `stl mo2 s`.

I still got the grep error from before but MO2 ran this time without any issues. Also, looks like all my games were detected.

Here's the terminal output for reference:

```
[desmond@soulengine .config]$ stl mo2 s
grep: /mnt/j-drive/SteamLibrary/steamapps/compatdata/1091500/pfx/system.reg: No such file or directory
Tuesday 21 September 2021 09:14:01 PM IST INFO - startMO2 - Starting '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe' in standalone mode
[desmond@soulengine .config]$
```

**Comment by frostworx** [comment]
Ok, so looks like current master is at that stage where it worked before my trip - neat!

I still wonder where your grep error comes from.
Does the file exist? The only part of the code where the file is grepped is here: https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L10091
and the grep would be skipped if the file does not exist.

**Comment by desmond27** [comment]
The file isn't there. This is Cyberpunk 2077's prefix. Now that I think about it, it crashes with the latest Proton-GE, so I think the prefix is not really "complete" so to speak. 

Besides, I am facing another issue, but perhaps this is unrelated to STL:

MO2 seems to crash when running from within Steam. I have configured STL to start in GUI mode in the Game Options.

Here's the contents of `startMO2_Mod.Organizer-2.4.2.exe.log` from `/dev/shm/stl`. I am not sure whether this needs to be fixed from within STL or I need to create a new prefix for either MO2 or the game.

```
mod organizer done
3.709:ERROR:dxva_video_decode_accelerator_win.cc(1399)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: Module not found. (0x7E)
[412:416:0921/211403.710:ERROR:dxva_video_decode_accelerator_win.cc(1407)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Module not found. (0x7E)
[412:416:0921/211403.810:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 8
```

Edit: Ok, it seems the issue was with Proton 6.3-6, I changed the proton version to Proton-GE-6.16 and MO2 starts now.

**Comment by desmond27** [comment]
So, I am kind of back to square one.

I managed to run MO2 from Steam (setting `stl %command%`). I then stopped it and tried to run it standalone to install some mods. Now I get this:

```
[desmond@soulengine stl]$ stl mo2 s
grep: /mnt/j-drive/SteamLibrary/steamapps/compatdata/1091500/pfx/system.reg: No such file or directory
grep: /home/desmond/.steam/root/steamapps/appmanifest_1580130.acf
/home/desmond/.steam/root/steamapps/appmanifest_1245040.acf
/home/desmond/.steam/root/steamapps/appmanifest_228980.acf
/home/desmond/.steam/root/steamapps/appmanifest_1493710.acf
/home/desmond/.steam/root/steamapps/appmanifest_4580.acf
/home/desmond/.steam/root/steamapps/appmanifest_1420170.acf
/mnt/f-drive/steamlinux/steamapps/appmanifest_228980.acf
/mnt/f-drive/steamlinux/steamapps/appmanifest_262060.acf
/mnt/h-drive/SteamLibrary/steamapps/appmanifest_418370.acf
/mnt/h-drive/SteamLibrary/steamapps/appmanifest_858280.acf
/mnt/h-drive/SteamLibrary/steamapps/appmanifest_961940.acf
/mnt/h-drive/SteamLibrary/steamapps/appmanifest_996510.acf
/mnt/j-drive/SteamLibrary/steamapps/appmanifest_1091500.acf
/mnt/j-drive/SteamLibrary/steamapps/appmanifest_110800.acf
/mnt/j-drive/SteamLibrary/steamapps/appmanifest_271590.acf
/mnt/j-drive/SteamLibrary/steamapps/appmanifest_356190.acf
/mnt/j-drive/SteamLibrary/steamapps/appmanifest_474960.acf
/mnt/k-drive/SteamLibrary/steamapps/appmanifest_1017900.acf
/mnt/k-drive/SteamLibrary/steamapps/appmanifest_1089130.acf
/mnt/k-drive/SteamLibrary/steamapps/appmanifest_1172380.acf
/mnt/k-drive/SteamLibrary/steamapps/appmanifest_281610.acf
/mnt/k-drive/SteamLibrary/steamapps/appmanifest_412020.acf
/mnt/k-drive/SteamLibrary/steamapps/appmanifest_72850.acf
/mnt/k-drive/SteamLibrary/steamapps/appmanifest_813780.acf
/mnt/k-drive/SteamLibrary/steamapps/appmanifest_976730.acf
/mnt/ssd-ext4/SteamLibrary/steamapps/appmanifest_594570.acf
/mnt/ssd-ext4/SteamLibrary/steamapps/appmanifest_673880.acf
/mnt/ssd-ext4/SteamLibrary/steamapps/appmanifest_291650.acf
/mnt/ssd-ext4/SteamLibrary/steamapps/appmanifest_489830.acf
/mnt/ssd-ext4/SteamLibrary/steamapps/appmanifest_933110.acf
/mnt/ssd-ext4/SteamLibrary/steamapps/appmanifest_570.acf
/mnt/ssd-ext4/SteamLibrary/steamapps/appmanifest_570940.acf
/mnt/ssd-ext4/SteamLibrary/steamapps/appmanifest_1536610.acf
/mnt/ssd-ext4/SteamLibrary/steamapps/appmanifest_239030.acf
/mnt/ssd-ext4/SteamLibrary/steamapps/appmanifest_782330.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_440.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_2200.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_599390.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_1070560.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_730.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_396750.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_22380.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_377160.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_611500.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_1113280.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_814380.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_1054830.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_457140.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_292030.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_1391110.acf
/mnt/sshd-ext4/SteamLinux/steamapps/appmanifest_238320.acf: No such file or directory
Tuesday 21 September 2021 11:08:35 PM IST INFO - startMO2 - Starting '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe' in standalone mode
[desmond@soulengine stl]$
```
MO2 now does not start. Here's the log from /dev/shm/stl/stl.log:

```
Tuesday 21 September 2021 11:08:34 PM IST INFO - createDefaultCfgs - setSteamPaths:
Tuesday 21 September 2021 11:08:34 PM IST INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/stl/steampaths.txt'
Tuesday 21 September 2021 11:08:34 PM IST WARN - updateEditor - 'xdg-open' selected as editor or configured editor not found - trying to find an installed editor installed
Tuesday 21 September 2021 11:08:34 PM IST SKIP - updateEditor - No valid editor found - leaving 'xdg-open'
Tuesday 21 September 2021 11:08:34 PM IST INFO - listAllSettingsEntries - '/dev/shm/stl/setentries.txt' already exists - nothing to do
Tuesday 21 September 2021 11:08:34 PM IST INFO - createDefaultCfgs - STOP
Tuesday 21 September 2021 11:08:34 PM IST INFO - initOldProtonArr - Creating an initial array with available Proton versions using the file '/dev/shm/stl/ProtonCSV.txt' which was created during a previous run
Tuesday 21 September 2021 11:08:34 PM IST INFO - initFirstProton - Initializing Proton
Tuesday 21 September 2021 11:08:34 PM IST INFO - initFirstProton - Initial Proton version 'FIRSTUSEPROTON' from '/home/desmond/.config/stl/default_template.conf' is 'proton-6.3-6c'
Tuesday 21 September 2021 11:08:34 PM IST INFO - prepareMO2 - Updating/creating ModOrganizer instances
Tuesday 21 September 2021 11:08:34 PM IST SKIP - checkInstalledMO2Games - '/mnt/f-drive/steamlinux/steamapps/compatdata/262060/pfx' missing - looks like the game was removed or never started yet
Tuesday 21 September 2021 11:08:34 PM IST SKIP - manageMO2GInstance - ModOrganizer instance 'Cyberpunk 2077' already exists
Tuesday 21 September 2021 11:08:34 PM IST SKIP - manageMO2GInstance - ModOrganizer instance 'Fallout 4' already exists
Tuesday 21 September 2021 11:08:34 PM IST SKIP - manageMO2GInstance - ModOrganizer instance 'New Vegas' already exists
Tuesday 21 September 2021 11:08:34 PM IST SKIP - manageMO2GInstance - ModOrganizer instance 'Skyrim Special Edition' already exists
Tuesday 21 September 2021 11:08:34 PM IST SKIP - manageMO2GInstance - ModOrganizer instance 'Skyrim' already exists
Tuesday 21 September 2021 11:08:34 PM IST SKIP - manageMO2GInstance - ModOrganizer instance 'New Vegas' already exists
Tuesday 21 September 2021 11:08:34 PM IST SKIP - manageMO2GInstance - ModOrganizer instance 'The Witcher 3 Wild Hunt' already exists
Tuesday 21 September 2021 11:08:34 PM IST INFO - checkInstalledMO2Games - Found game 'Cyberpunk 2077 (1091500)' with pfx '/mnt/j-drive/SteamLibrary/steamapps/compatdata/1091500/pfx'
Tuesday 21 September 2021 11:08:34 PM IST SKIP - checkInstalledMO2Games - '/mnt/f-drive/steamlinux/steamapps/compatdata/262060/pfx' missing - looks like the game was removed or never started yet
Tuesday 21 September 2021 11:08:34 PM IST INFO - checkInstalledMO2Games - Found game 'Fallout 4 (377160)' with pfx '/mnt/sshd-ext4/SteamLinux/steamapps/compatdata/377160/pfx'
Tuesday 21 September 2021 11:08:34 PM IST INFO - checkInstalledMO2Games - Game Dir is '/mnt/sshd-ext4/SteamLinux/steamapps/common/Fallout 4' - adding the windows variant into ModOrganizer registry, because it is required for this game
Tuesday 21 September 2021 11:08:34 PM IST INFO - checkInstalledMO2Games - Found game 'New Vegas (22380)' with pfx '/mnt/sshd-ext4/SteamLinux/steamapps/compatdata/22380/pfx'
Tuesday 21 September 2021 11:08:34 PM IST INFO - checkInstalledMO2Games - Game Dir is '/mnt/sshd-ext4/SteamLinux/steamapps/common/Fallout New Vegas' - adding the windows variant into ModOrganizer registry, because it is required for this game
Tuesday 21 September 2021 11:08:34 PM IST INFO - checkInstalledMO2Games - Found game 'Skyrim Special Edition (489830)' with pfx '/mnt/ssd-ext4/SteamLibrary/steamapps/compatdata/489830/pfx'
Tuesday 21 September 2021 11:08:34 PM IST INFO - prepMO2GameSym - Removing symlink '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/cache' pointing to '/mnt/k-drive/SteamLibrary/steamapps/compatdata/72850/pfx/drive_c/users/steamuser/Local Settings/Application Data/cache'
Tuesday 21 September 2021 11:08:34 PM IST INFO - prepMO2GameSym - Creating Symlink from '/mnt/ssd-ext4/SteamLibrary/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/Local Settings/Application Data/cache' to '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/cache'
Tuesday 21 September 2021 11:08:34 PM IST SKIP - prepMO2GameSym - Not creating Symlink from '/mnt/ssd-ext4/SteamLibrary/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/Local Settings/Application Data/ModOrganizer' to '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer', because '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer' is a real directory
Tuesday 21 September 2021 11:08:34 PM IST INFO - prepMO2GameSym - Removing symlink '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/LOOT' pointing to '/mnt/k-drive/SteamLibrary/steamapps/compatdata/72850/pfx/drive_c/users/steamuser/Local Settings/Application Data/LOOT'
Tuesday 21 September 2021 11:08:34 PM IST INFO - prepMO2GameSym - Creating Symlink from '/mnt/ssd-ext4/SteamLibrary/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/Local Settings/Application Data/LOOT' to '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/LOOT'
Tuesday 21 September 2021 11:08:34 PM IST INFO - checkInstalledMO2Games - Game Dir is '/mnt/ssd-ext4/SteamLibrary/steamapps/common/Skyrim Special Edition' - adding the windows variant into ModOrganizer registry, because it is required for this game
Tuesday 21 September 2021 11:08:34 PM IST INFO - checkInstalledMO2Games - Found game 'Skyrim (72850)' with pfx '/mnt/k-drive/SteamLibrary/steamapps/compatdata/72850/pfx'
Tuesday 21 September 2021 11:08:34 PM IST INFO - prepMO2GameSym - Removing symlink '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/cache' pointing to '/mnt/ssd-ext4/SteamLibrary/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/Local Settings/Application Data/cache'
Tuesday 21 September 2021 11:08:34 PM IST INFO - prepMO2GameSym - Creating Symlink from '/mnt/k-drive/SteamLibrary/steamapps/compatdata/72850/pfx/drive_c/users/steamuser/Local Settings/Application Data/cache' to '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/cache'
Tuesday 21 September 2021 11:08:34 PM IST SKIP - prepMO2GameSym - Not creating Symlink from '/mnt/k-drive/SteamLibrary/steamapps/compatdata/72850/pfx/drive_c/users/steamuser/Local Settings/Application Data/ModOrganizer' to '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer', because '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer' is a real directory
Tuesday 21 September 2021 11:08:34 PM IST INFO - prepMO2GameSym - Removing symlink '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/LOOT' pointing to '/mnt/ssd-ext4/SteamLibrary/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/Local Settings/Application Data/LOOT'
Tuesday 21 September 2021 11:08:34 PM IST INFO - prepMO2GameSym - Creating Symlink from '/mnt/k-drive/SteamLibrary/steamapps/compatdata/72850/pfx/drive_c/users/steamuser/Local Settings/Application Data/LOOT' to '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/LOOT'
Tuesday 21 September 2021 11:08:34 PM IST INFO - checkInstalledMO2Games - Game Dir is '/mnt/k-drive/SteamLibrary/steamapps/common/Skyrim' - adding the windows variant into ModOrganizer registry, because it is required for this game
Tuesday 21 September 2021 11:08:34 PM IST INFO - checkInstalledMO2Games - Found game 'TTW (22380)' with pfx '/mnt/sshd-ext4/SteamLinux/steamapps/compatdata/22380/pfx'
Tuesday 21 September 2021 11:08:34 PM IST INFO - checkInstalledMO2Games - Game Dir is '/mnt/sshd-ext4/SteamLinux/steamapps/common/Fallout New Vegas' - adding the windows variant into ModOrganizer registry, because it is required for this game
Tuesday 21 September 2021 11:08:34 PM IST INFO - checkInstalledMO2Games - Found game 'The Witcher 3 Wild Hunt (292030)' with pfx '/mnt/sshd-ext4/SteamLinux/steamapps/compatdata/292030/pfx'
Tuesday 21 September 2021 11:08:35 PM IST INFO - prepareMO2 - No ModOrganizer instance provided - searching last one found in '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/nxmhandler.log'
Tuesday 21 September 2021 11:08:35 PM IST INFO - prepareMO2 - Found 'Fallout4' as last used game in '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/nxmhandler.log', so using instance ''
Tuesday 21 September 2021 11:08:35 PM IST INFO - manageMO2GInstance - Could not find game name for '' - starting regularly with default instance
Tuesday 21 September 2021 11:08:35 PM IST INFO - prepareMO2 - No ModOrganizer instance provided
Tuesday 21 September 2021 11:08:35 PM IST INFO - setMO2DLMime - Desktopfile '/home/desmond/.local/share/applications/ModOrganizer-stl-dl.desktop' looks to be up2date
Tuesday 21 September 2021 11:08:35 PM IST INFO - startMO2 - Starting '/home/desmond/.config/stl/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe' in standalone mode
```

**Comment by frostworx** [comment]
Ok,
that paste had some good hints:
- looks like a real `LOOT` dir is required in the MO2 pfx, so games using it do not z-fight with symlinking
- a real `ModOrganizer`dir should not _(already)_ exist in a game pfx, as it needs to be symlinked to that from the MO2 pfx
  _(probably the best and easiest solution would be to rename it)_

Regarding your launch problem:
It looks like
`Tuesday 21 September 2021 11:08:35 PM IST INFO - manageMO2GInstance - Could not find game name for '' - starting regularly with default instance`
is the problem here and `prepAllMO2Games` passes an empty line to `createAllMO2Instances`. This needs to be fixed ~~in 2 functions~~, but please also check the output of `stl mo2 li` _(or directly `stl mo2 li | cut -d ';' -f1`)_ for empty lines

_(please append logs instead of pasting them, it is much easier to read/work with)_

General note @all:
I will have much less time for working on stl in a few weeks, so contributors welcome to keep it alive!

**Comment by frostworx** [comment]
possible fixes @ previous post: https://github.com/frostworx/steamtinkerlaunch/commit/acb6ef9b442b82cef30006b4255d695a575fd2a5

**Comment by desmond27** [comment]
Here's the output:

```
[desmond@soulengine ~]$ stl mo2 li | cut -d ';' -f1
1091500
377160
22380
489830
72850
22380
292030
[desmond@soulengine ~]$
```
I haven't tried the latest fixes though.

**Comment by frostworx** [comment]
[this](https://github.com/frostworx/steamtinkerlaunch/issues/306#issuecomment-927820004) is also valid for MO2 of course

**Comment by desmond27** [comment]
I tried MO2 last week and it appears to work fine. I tested with Fallout 4 for now and installed MCM and it works. Will try with more mods and the other games soon when I manage to import my existing MO2 profiles and mods. I wish there were a simpler way to do this.

Is there any way to install MO2 (prefix) to a separate directory than ~/.config? I generally try not to use my home partition for this and prefer running my larger prefixes in a separate drive dedicated to games. Plus my MO2 mod list goes into multiple gigabytes and I'd rather not store them in my home directory.

**Comment by frostworx** [comment]
Sure, you can set the "Mod Organizer 2 compatdata" _(`MO2COMPDATA`)_ to whatever directory in the global menu/config.

**Comment by desmond27** [comment]
Do I need to run `stl mo2 s` again after setting that?

**Comment by frostworx** [comment]
As this creates a clean wineprefix/compatdata and installs/symlinks MO2 into it,
it is probably the better idea than moving the whole existing compatdata to the new location.
This might work as well though, so why not try it?

**Comment by frostworx** [comment]
The [Vortex](https://github.com/frostworx/steamtinkerlaunch/issues/306) rewrite is pretty much feature complete.
Maybe some more changes to the Mod Organizer 2 implementation _(they share many functions now :))_,
I might just disable the silent mode as I personally prefer [Vortex](https://github.com/frostworx/steamtinkerlaunch/issues/306) and apparently feedback @ MO2 was pretty low,
and then I'll probably push the monster commit somewhere in the 1st third of October.
Any fixable reported issue will make it into the end of October major release _(when I find the time)_

**Comment by desmond27** [comment]
I was really busy over the last week so never really came around to testing this out. Plus I have other personal obligations over the next few days so perhaps I can only test this out next week.

**Comment by frostworx** [comment]
No worries, I didn't mean you @desmond27  Apparently you were the only one who tested something.
Friendly feedback by @Septimius-Severus appreciated as well of course!

**Comment by frostworx** [comment]
landed: https://github.com/frostworx/steamtinkerlaunch/commit/eda1929798b4d61eb7580c4fb3f592f81bd16da9

**Comment by rawardy** [comment]
It appears launching SKSE on Skyrim SE, through MO2 does not work. No SKSE loads at all and I can't get it working if I use MO2. Confirmed working through Vortex with all the same Proton versions etc.

 Interestingly after closing out of Vortex pop-up first and using the subsequent SKSE detection pop-up to select "save and launch with SKSE64" option MO2 will no longer work (tried to see if maybe that would fix). Selecting MO2 GUI after this point boots the game straight up with SKSE, bypassing MO2 forever.
 
 Tried all these various combinations using a BTRFS snapshot with everything ready to test from scratch to try and get SKSE working through MO2, trying multiple methods like the Vortex example above, but no luck..
 
  Enderal SE installed through Steam does work through MO2 with SKSE but the game starts with SKSE automatically always, no matter how you launch it. Don't know how SureAI achieved this with their install. So I don't think that's relevant but poss worth mentioning.

**Comment by desmond27** [comment]
I haven't tried Skyrim SE yet, but I tried running F4SE for Fallout 4 and it ran without any issues.

Will try Skyrim SE and report either today or tomorrow.

**Comment by rawardy** [comment]
Thanks, I should note that I'm new to stl/proton and modding Skyrim on Linux (experienced with Windows from a few years ago). I've used Lutris till now for my gaming needs. I cleared my stl .config and reinstalled everything from scratch yesterday before trying again to be sure.
 
  Did 'stl mo2 s' after installing Proton-6-17-STL-1 for MO2 in stl settings first (noticed on that reinstall that proton version was now selected by default in settings). Skyrim runs with 6-16-GE-1 (newest GE version appears to have broken Skyrim). So apologies if this is simply a screw up on my side of things.

**Comment by desmond27** [comment]
If I understand correctly, when running `stl mo2 s`, the version of proton used is different than the version of proton used when running from within Steam. When running from Steam, STL will use the proton version defined in the compatibility settings for that game, while running directly from the command line it will run using a custom version.

**Comment by rawardy** [comment]
I see. I've tried a simple stl mo2 i and a few different proton versions but with no success. (On the plus side the latest GE proton is loading Skyrim just fine now).

**Comment by frostworx** [comment]
Hi all,
thanks for your help here @desmond27 👍!
@rawardy,  @desmond27 is right. When starting MO2 via `stl mo2 s` it is using its own compatdata/pfx and its own proton version _(by default Proton-6-17-STL-1)_ and when starting through steam MO2 is started in the game's compatdata/pfx with the game's proton.

Looks like the sort order needs to be changed, so the "Use SKSE" requester also needs to respect MO2, so MO2 is no longer skipped.
Might be good to know how you tried to start the skse exe and which version you were using.
I'll try to find out more soon.

**Comment by rawardy** [comment]
I didn't have Vortex installed or enabled when I first started noticing the issue. I only installed Vortex to trigger the "Use SKSE" requester as a hunch that it might fix the problem with SKSE not launching through MO2. I'm using a completely clean fresh install Steam version of Skyrim SE. I have only added the latest "SE build 2.0.19 (runtime 1.5.97)" from here..
 
 https://skse.silverlock.org/
 
  I install SkyUI latest in MO2 to see whether SKSE throws up a "not loaded" when loading the game.
  
   It appears, once installed, Steam launches SKSE automatically, (bypassing the usual Skyrim launcher), whether launched through Proton compat directly or by skipping loading MO2 all together when booted through stl.. I don't know if Steam does this by default on Windows or if this is a Proton thing (or poss a Proton GE specific thing).

**Comment by rawardy** [comment]
I should also add that launch through SKSE does get added correctly to MO2 automatically when installed and I've double checked that the path to the skse64_loader.exe is correct. So MO2 has no issues detecting that SKSE is installed. It just can't launch it for whatever reason. Any time I've tried something weird, (like bringing up the Vortex triggered use SKSE prompt) to try and get it to work and failed; I've restored my root and home partition snapshots to return to the setup as described above. Keep things simple that way.

 To sum up. On booting Skyrim SE added in the MO2 category if I choose to skip loading MO2 GUI when prompted SKSE loads correctly. Loading MO2 GUI and launching SKSE through that does not start SKSE for some reason.

**Comment by frostworx** [comment]
You need to use a newer verison, the currently latest from https://skse.silverlock.org/ doesn't work with proton.
There were several custom builds which worked, but fortunately a working official version has been release just a few days ago:
https://www.reddit.com/r/SteamPlay/comments/q0a5mt/psaskyrim_se_good_news_for_those_who_want_to_use/

Independantly from the skse version, I'll make the stl-internal SKSE detection MO2 compatible as well.

**Comment by rawardy** [comment]
Works like a charm! Thanks! Amazing that the week I decide to try and mod Skyrim on Linux, stl, (which I wasn't aware of previously), gets MO2 support and now this happens. Luck. Thanks for all the work you've put into this!

**Comment by frostworx** [comment]
Thank you for the feedback! Very appreciated! :)

**Comment by frostworx** [comment]
Just started to make some changes to make the SKSE detection MO2 compatible, until I found out that this doesn't make much sense at all, as MO2 itself is started anyway _(which in turn starts the SKSE exe)_. 😀
The reason why MO2 was skipped in your attempt @rawardy was simply, because the custom command is started before the main start command. Only the latter has the MO2 hook though, which makes sense, as MO2 can start the exe which would have started on its own. Long story short, I'll simply disable the custom launch when MO2 is enabled as well and everything should be fine. _(hehe, elaborating this was more work than the actual fix)_
edit: should work: https://github.com/frostworx/steamtinkerlaunch/commit/bdb6f3822e8144091e072d504adf3c9f77702c8f

**Comment by rawardy** [comment]
Using Vortex and MO2 for the same game is a bad idea anyway. Like I said earlier I used the Vortex induced prompt to choose the custom command out of pure desperation and the ability to easily roll back my system. With the up to date SKSE everything is working perfectly using only MO2.
 
  Got Enderal SE (Nexus ver) with STEAMIN ENB all running perfect. Spent so much time attempting to get all that working from 0 knowledge of Proton (was on the Lutris side). When it worked for the first time after trying so many things  it was a pretty satisfying feeling.
  
   Note to anyone who is interested don't try and mod the Steam version of Enderal, you can't update SKSE and I believe it confuses Proton if you want to try and add an up to date enb because of the older version already included. Use Skyrim SE and install Enderal manually from the Enderal Nexus page with up to date SKSE in MO2.

**Comment by frostworx** [comment]
Hehe, Vortex and MO2 together is a bad idea indeed. But The "custom program" enabled through Vortex SKSE question can also be used without Vortex, therefore I disabled it with enabled MO2.

Thanks for the Enderal hint! Still a game I definitely need to play _(only played the beginning so far, but Nehrim was  great)_.
And definitely need to play it with STEAMIN ENB, it looks amazing!

**Comment by rawardy** [comment]
Yeah STEAMIN does look amazing! Only confirmed that the enb loads correctly so far though. Now I've passed that hurdle I'm working through the extensive modlist to go along with it before I can see it in all its intended glory...
 
  Got almost everything installed. Hopefully be finished later today. If you get round to trying it out, you want to add both the Enderal main menu and loading screen mods for enb to fix the oversaturation on those, (easily searchable on nexus). Those appear to be the only mods the author has missed off the modlist judging by the comments on the mod page.
  
  If you are using MO2 make sure you toggle "Enderal Downloads" to "True" under Skyrim SE on the Plugins tab of the settings before adding mods. That's easily missed in the Enderal SE instructions on Nexus.

**Comment by frostworx** [comment]
Thanks for all the hints! Also, good to hear MO2 seems to work as expected! :)

**Comment by frostworx** [comment]
Seems to work so far -  _closing here_
**Thanks all for testing!**

I'll leave the unfinished/improvable parts _as-is_
- `function dlMod2nexurl`
- `function disabledWIPSilentMode` _(commented out via function)_

**Comment by frostworx** [comment]
Reopening for generic MO2 problems _([reason](https://www.reddit.com/r/SteamTinkerLaunch/comments/qaf5dj/whats_the_correct_way_to_launch_skyrim_se_when/))_.
I hope you can help each other here a bit :)
Edit: Alternatively, you can use the _(empty)_ [discussion board](https://github.com/frostworx/steamtinkerlaunch/discussions) of course.

**Comment by frostworx** [comment]
Closing here again :)
Feel free to use the discussion board if you like.
Alternatively, if you have some modding hints which might be helpful for others, they could be shared in the [Modding](https://github.com/frostworx/steamtinkerlaunch/wiki/Modding) wiki

**Comment by frostworx** [comment]
Any chance someone can give a hint [here](https://github.com/frostworx/steamtinkerlaunch/issues/338)?
Skyrim doesn't launch when started through MO2 - no matter if mods are enabled or not.
It works standalone though

**Comment by desmond27** [comment]
I'm facing an issue when running MO2 via STL: MO2 is unable to find Steam even though it's running.

When I press play in MO2 after running from within Steam, I get a dialog box that says "This program requires Steam" with the following options: "Start Steam", "Continue without starting Steam, the program might fail to run." and "Cancel". Clicking on "Start Steam" yields an error: The file 'C:\Program files (x86)\Steam\Steam.exe' does not exist. Clicking on "Continue without starting Steam" does nothing.

I used the MO2COMPDATA environment variable to create a MO2 prefix in a separate folder, though I don't think this is the issue.

I tested running both F4SE and SKSE and the result is the same.

I remember it had worked when I last tested when the prefix was in ~/.config/stl

Anyone else facing this problem?

**Comment by frostworx** [comment]
Coincidence, that I found your problem, @desmond27. I only wanted to reopen this issue again for generic MO2 problems and haven't seen this before.
So does 'C:\Program files (x86)\Steam\Steam.exe' actually exist? Afair it was automatically created by Proton, maybe something changes on Proton side and needs to be created manually now.

**Comment by desmond27** [comment]
I have actually tinkered around with this issue a bit more since I last reported here. The observations in my above comment is a bit incorrect. I get that issue when running MO2 in standalone mode, which I think is expected (or that it doesn't matter since the sole purpose of the standalone mode is to manage games and mods). That is if I were to use the MO2COMPDATA env variable and then run in standalone mode then MO2 throws the unable to find Steam error.

If I installed MO2 as follows then I run into some trouble:

```
$ MO2COMPDATA=/mnt/k-drive/stl-mo2-compdata stl mo2 s
```

When I install like this, MO2 runs okay when running using `stl mo2 s` or from the STL menu after running the game from Steam. It detects all the games as expected and creates instances for each of them. I am also able to install mods (tested with Fallout 4 and Skyrim LE).

But if I were to enable MO2 gui mode in the STL game options, then run the game and click on the MO2 gui button, MO2 starts but it does not detect any instances and prompts me to create a new one. It is as if standalone mode never ran before. Thus, I am unable to proceed beyond this step. I could try to create a new instance but then what would be the point or creating the instances before?

Note that this issue does not occur when using the default prefix in ~/.config/stl.

**Comment by frostworx** [comment]
Yes, as you already founbd yourself standalone mode is not meant to work with launching games - some work, most don't because Steam is not running/detected, so it is not recommended to start a game in that mode.

When you use the inline variable MO2COMPDATA, it is only valid for this one command (so it uses it as expected and installs into this location). stl itself doesn't know that you altered MO2COMPDATA on the fly via override and therefore doesn't know anything about your `/mnt/k-drive/stl-mo2-compdata`.
I expect it to work correctly when you set MO2COMPDATA directly in the global.conf (f.e. via stl settings).

**Comment by desmond27** [comment]
I did what you said and it seems like the issue is the same:

![image](https://user-images.githubusercontent.com/3539261/141143989-dbdaf2ae-d13f-419c-b8dc-d4e3c5cdcfdf.png)

I ran `stl settings` then clicked on `Global` and then set the MO2 compatdata directory to an empty directory. I then installed MO2 again using `stl mo2 s`. It got installed and ran no problem. Then I started Fallout 4 from Steam and set MO2 mode to GUI in the MO2 settings. But I get the above error when I run MO2.

I went into the new prefix and followed that path and I see that that path is valid and I can see the Fallout 4 instance files and directories there:

```
[desmond@soulengine Fallout 4]$ pwd
/home/desmond/.config/stl/compatdata/Fallout 4/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/Fallout 4
```
and the symlink to the new compatdata directory I created looks okay:
```
lrwxrwxrwx 1 desmond desmond   88 Nov 10 21:08 ModOrganizer -> /mnt/sshd-ext4/stl-mo2-compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer
```

**Comment by frostworx** [comment]
I'll try to reproduce this, but I see no obvious reason, why this should fail from stl side.
I think it could be possible, that proton doesn't accept that path because it is not in your home.
If you want, you can test if f.e. `/home/desmond/mo2` works as expected.
Just started a test with `/tmp/mo2/` as compatdata

**Comment by frostworx** [comment]
yes, MO2 in `/tmp/mo2/` in compatdata works as expected and launching the FO4 through Steam->MO2 works as expected as well, so I assume my asumption with proton rejecting certain paths is correct.

**Comment by desmond27** [comment]
So, does this mean that there is some issue with the Proton version I am using? I tested with Proton 6.16-GE-1 and 6.3-7. What version of Proton have you used for testing this?

I'll try installing to /tmp/mo2 and revert as well.

Edit:

It's weird. It runs okay when I install to /tmp/mo2 but it does not run run running from any of my mounted drives. It's weird because a lot of my games run with compatdata directories in the mounted drives.

**Comment by frostworx** [comment]
I does mean that **I think** that your issue is that some (probably newer) proton versions prevent the user from using specific directories _(or better explicitely just allows specific directories)_. I don't know which proton version does so and which not, but I used latest Proton-GE, which very likely does the same _(`/tmp/` is not blocked and therefore the test works)_.
Very likely this is documented somewhere online, don't have an url to share though.

**Comment by frostworx** [comment]
@ your edit:
that is a different scenario: your compatdata are whitelisted for proton of course, no matter where they are.

**Comment by frostworx** [comment]
TL;DR:
I'd assume (currently; might change) everything in
- $HOME
- any official compatdata _(or maybe simply everything in every SteamLibrary path defined in Steam - you could try that)_
- /tmp/
- _(probably also /run/ and /dev/shm/)
is accepted by proton

**Comment by desmond27** [comment]
Yeah, what I ended up doing is creating a portable instance in C:\Modding\MO2 in the MO2 compatdata. This is already symlinked to Fallout 4's compatdata, so no issues there. I'll have to check and see whether this setup works with multiple games or not since the instances are overridden.

**Comment by frostworx** [comment]
@all: You might be interested in this issue/fix: https://github.com/frostworx/steamtinkerlaunch/issues/349
