### ISSUE TITLE
Significant performance penalty when using MO2 for Skyrim SSE

### ISSUE THREAD

**Issue by Erdragh** [sonic2kk/steamtinkerlaunch#446]
## Basic info:
- OS: EndeavourOS
- Kernel: 5.17.1-zen
- DE: Plasma 5.24.4
- CPU: AMD Ryzen 2700x not overclocked
- GPU: NVIDIA Geforce RTX 2070 not overclocked
- 32GB of RAM
- SteamTinkerLaunch v9.2 (installed from the AUR)
- The SteamLibrary folder in which SkyrimSE is installed is located on another hard drive at `/run/media/erdragh/LinuxVolume/SteamLibrary`
- I set the base directory for the mo2 instance to be on `Z:\run\media\erdragh\LinuxVolume\SkyrimModding\`, because I wanted my mods to not fill up my SSD.
## Description of issue:
Running the game from Steam works fine. I do not get any performance issues and everything runs buttery smooth. When starting mo2 with `steamtinkerlaunch mo2 s` and then running SKSE the game loads fine and loads all installed mods, but there is a significant performance penalty when looking in certain directions or being in certain locations.

Here is a video of the issue:
https://youtu.be/MIENRxv5IvY

This is the [steamtinkerlaunch.log](https://gist.github.com/Erdragh/c0e40678f9e01d59329fa8b813e1d107)

I do not know where the log for the start of mo2 would be located as that was not stated in #93 and I wasn't able to find it.
## My assumption:
I think that this is an issue with certain system libraries and the such. STL's mo2 installation uses a separate prefix from what I can tell and when installing SkyrimSE from steam and launching it for the first time it installs (and afaik configures) the dependencies in Skyrim's own prefix. Since mo2 does not seem to use that same prefix (I think?) there could be some dependency issues. This could also be completely wrong because how would Skyrim start without these dependencies.
## More information:
The installation of mo2 also fails to load enb if it is installed. The video linked above does not have it installed, but I tested it prior with enb and it did not seem to load. It also does not detect Steam as running, but afaik that is the intended/expected behavior.

I have also read that using winetricks/protontricks to install some dependencies like certain d3dXX_compiler.dll files would solve the issue with enbs not loading. Maybe it would also solve this issue, but I'm not sure how to issue these commands as most posts I found on the internet assume that one is using the system wine installation to run MO2, which is not the case with stl, as it seems to use it's own Proton version (`Proton-6.17-STL-1` as far as the folder it is in is correctly named) for running mo2.
## Also:
- I am currently reinstalling SkyrimSE completely (as in uninstall > remove folder & compatdata folder > install) and will update this issue as soon as possible
- Is there a way to uninstall stl's mo2 so I can do a completely clean reinstall?

**Comment by frostworx** [comment]
`steamtinkerlaunch mo2 s` is not meant to start a game from within MO2 - check the [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Mod-Organizer-2)
When the game starts here (I'd guess most games don't) it is running in the wrong compatdata with the wrong proton version.

The custom compatadata path is only for modding the game, the game still is started regularly within its own compatdata using its own proton version configured.

For a complete reinstall of the custom mo2 installation, simply rename ~/.config/steamtinkerlaunch/mo2
and install it again _(files from games/game compatdata dirs are symlinked)_

Btw, current git master has multiple MO2 related changes - the custom Proton `Proton-6.17-STL-1` is fortunately no longer required, as dotnet now also installs correctly with newer GE-Proton versions _(the latest one is automatically downloaded/used if not configured otherwise)_
_(currently dotnet installation is disabled for MO2 completely though - it is not clear yet, if it is still required for internal MO2 functions)_

it is a proton issue when enb fails and unrelated to steamtinkerlaunch. It can be made to work with some customization though. _(I once considered enb support, but dropped the idea)_

**Comment by Erdragh** [comment]
Thanks for the quick response! I had completely missed that statement in the wiki. As soon as Skyrim is reinstalled I will try this and post another update here. As enb worked before when started through Steam I assume that enb will work just fine.

**Comment by frostworx** [comment]
IIRC you had to install `d3dcompiler_47.dll` for enb, but really can't help there.

**Comment by Erdragh** [comment]
Thanks and you don't have to, this issue is not about ENB :). While Skyrim is still downloading I wanted to try out Fallout 4. To start the game with MO2 I put it in the Steam Category aptly named "MO2". I wanted to run the stl launcher, but executing `steamtinkerlaunch launcher` results in no command output and being put back to a shell prompt and no interface opening. If there's an easy fix I'd like to know, if this is another issue I could do a more detailed report in a new issue.

When using the launch option "steamtinkerlaunch %command%" for Fallout 4 it starts the stl interface. If I choose to start the MO2 GUI I can install mods no problem. However If I start the game and skip the MO2 GUI the mods are not loaded. When running the game through the MO2 interface they are loaded, but apparently that's not how to start the game right? How would I start the game with the mods loaded if not through MO2? I'm sorry if this is a noob question and if I just read over another part of the wiki please feel free to just link me to it. 

Skyrim is still downloading

**Comment by frostworx** [comment]
Not sure why you run `steamtinkerlaunch launcher`. it is supposed to collect all your installed steam games and create a little launcher. It is not really a great feature, but more a side product of some other functions I once wrote :)
If this doesn't work for you, it might require some debugging _(logs)_

I do not recommend using `steamtinkerlaunch %command%` when using Windows games. Instead use steamtinkerlaunch as [compatibility tool](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Compatibility-Tool)
Anyway, when you start MO2 from the steamtinkerlaunch settings menu _(by clicking the "Mod Organizer 2" menu)_ you start again the editor only mode _(same as `steamtinkerlaunch mo2 s`)_ If I understood correctly you didn't do so.
A correct MO2 start through steam would be

- put the game in the Steam Category "MO2"
- launch the game using steamtinkerlaunch _(ideally as compatibility tool)_
- let the [Wait-Requester](https://github.com/frostworx/steamtinkerlaunch/wiki/Wait-Requester) timeout
- a separate MO2 requester should ask if you want to open MO2
- choose yes _(see * note below)_
- MO2 opens
  - you can start the game directly from MO2 here _(iirc - I do not use it)_
  - if you close MO2 instead the game should start anyway - with the mods applied _(iirc - I really do not use it)_

* _(the initial idea was to use MO2 without even open its gui - unfortunately this doesn't seem to work, so the "silent" mode is disabled in the code anyway)_

This is all indeed confusing, but imho currently the only sane possibility to start a game using MO2 directly from steam
(an easier per-game approach would be to install mo2 into every compatdata of each game, but this would require a dotnet installation in every compatdata which is often very unstable. also, you don't have the option to choose between games when modding within mo2)

good luck so far

**Comment by Erdragh** [comment]
Thanks! It seems to run fine now. I only sometimes get stutters or the audio cuts out. I will try and install the 3d sound mod and an enb and update here once again. Thanks for all the help so far :)

**Comment by Erdragh** [comment]
Small update: The functionality of closing MO2 and having the game launch seems to not work, as when I close it after about half a minute stl recognized that nothing is running anymore and stops itself. Also, so far ENB seems to work. Have not tried the sound mod yet.

**Comment by frostworx** [comment]
you're welcome.
once for audio dropouts in Bethesda games (often in FO3 iirc) installing xact _(using winetricks)_ helped/was required,
but I think this should work fine without native xact since some time. Maybe switching to GE-Proton helps here without any further overrides.
@ update:
Ah I see, ok maybe you really only can start it through MO2 - haven't touched it for a while.
thanks for the update :)

**Comment by Erdragh** [comment]
[The 3D sound mod](https://www.nexusmods.com/skyrimspecialedition/mods/1897) seems to work, but it does not solve the audio cutouts. Also I think I should be using proton-ge, as I've got it's binary aur package installed and can select it in steam. I'm using STL as the compatability tool though.
Also, from what I can tell the audio cutouts are in conjunction with short freezes, which may be the vulkan shaders compiling in the background, I'm not sure yet, as I've only just reinstalled Skyrim. They also may be completely unrelated to any graphical things.
I'm gonna record some footage of the audio cutouts and post them here, but so far I'm happy as this is the furthest I've gotten with modding Skyrim on Linux :)

**Comment by frostworx** [comment]
You can simply choose custom Proton builds (including all Proton-GEs) within steamtinkerlaunch _(also with automatic update)_
no need to install it globally using AUR.
both video and audio stutters are not steamtinkerlaunch related, I just try to help - no need to create and upload footage :)

**Comment by Erdragh** [comment]
I've got Proton-GE installed globally because I like to use it for basically all windows games, also it updates with yay -Syu so that's also a plus. I'm going to try installing Proton-GE via stl and if it still does the audio cutouts I will try installing xact with winetricks. I will post another update, but then I think we can lay this issue to rest :)

**Comment by frostworx** [comment]
true, initial issue is solved. happy tinkering

_(sometimes it is good to have multiple proton versions for testing. I like yay as well, but you always have the latest in this case)_

**Comment by Erdragh** [comment]
Ok so: [The sound issue still persits](https://youtu.be/INC-V4E6Czg) without xact, but after installing xact with winetricks it works flawlessly.

**Comment by Maxattax97** [comment]
I am in a very similar situation but with the original Skyrim ("Oldrim")... It is well known that changing your proton launch options to use `WINEDDLOVERRIDES="xaudio2_7=n,b" PULSE_LATENCY_MSEC=90 %command%` fixes the issue. Since I have to use the Proton that encapsulates MO2 (which I changed to `GE-Proton7-14`), I am stuck with limited options to set these arguments. Any advice? This is literally the last thing to get everything working. `xact`, `faudio`, and the 3D sound mod that @Erdragh listed did not work for me.

**Comment by Maxattax97** [comment]
Nevermind my previous comment, I am a noob to Steam Tinker Launch and didn't realize that it launches MO2 in a slightly different way if you wait for the launcher to time out. This second one behaves the way I need it to.

I would try to describe how I got this working for other people, but I honestly don't understand how I got my insane amalgamation of proton, configs, mods, and a million other things working so I would rather not mislead anyone... that's not a criticism of this project, it's just gosh darn difficult to run games in Wine sometimes, let alone mod them.

**Comment by ranisalt** [comment]
There's an issue with Vortex/MO2 and Skyrim AE (latest version): because of the crappy Bethesda mod manager, if you start the game through Steam, it disables several mods (notably, SkyUI) and there are no workarounds, at least so far. So, we must start the game through Vortex/MO2, but then it will not apply the settings for the game, it will have terrible performance, no gamemode, no mangohud, no custom Proton version, nothing.

It would fix the issue if Vortex/MO2 was executed with the same settings the game uses, possibly having them installed in the game prefix instead.

**Comment by Erdragh** [comment]
As far as I understand, the install location for MO2 gets symlinked into the wine prefix for the game, so when you run Skyrim from steam with stl as the compatibility tool while the game is in the "MO2" category it should give you the opportunity to open the MO2 gui, start the game from there and everything should work fine.

At least it does for me with:
- newest Skyrim Version available
- Latest SKSE available
- Latest enb binaries available
- MO2 updated to the newest version
- The mod-manager download button on the nexus working
- All Tools working perfectly well (LOOT, Nemesis, BodySlide, TexGen, DynDOLOD, EasyNPC)
- over 200 mods

You said something about abysmal performance, I had the same issue when I was starting MO2 with
```
steamtinkerlaunch mo2 start
```
(I think that's the command, haven't used it in a while)

If I understand things correctly, the above command is only intended to be used for managing mods, not for starting the game.
As far as I could tell I don't need to use that command for managing my mods and can just use the MO2 gui that opens by launching the game from steam.

**Comment by ranisalt** [comment]
Right, but does it work the same if I use Vortex instead? And by category, do you mean collection?

Edit: yes, [according to this gif](https://github.com/frostworx/steamtinkerlaunch/wiki/Vortex#steamtinkerlaunch-vortex-gif) collections are being called category in the docs

Edit 2: it does not work. Using STL as compatibility tool, game in the Vortex collection, nothing in the launch command, it just skips Vortex and opens the game directly, incurring in the issue I mentioned. It may be worth noting that the mod manager download button has never worked for me.

**Comment by Erdragh** [comment]
That sounds like it doesn't even use stl. There's another way to have a game start with stl: change the startup options to be something like:
```
steamtinkerlaunch %command%
```
or replace steamtinkerlaunch with stl, however you can run commands on your system (I have stl installed from the AUR on EndeavourOS, `stl` as a command doesn't exist for me, but for others it apparently does)

It has to be noted that this is not the preferred way, but in my limited testing it worked just as well.

**Comment by ranisalt** [comment]
No dice. It just opens the regular game launcher instead, even when using `steamtinkerlaunch %command%`.

**Comment by Erdragh** [comment]
Then I'd say you should make a new issue about this topic because

1) It's not about performance loss anymore, it's now about STL not launching at all
2) This issue is closed
3) you'll more likely get a response from the actual maintainer - I'm just a random guy who uses STL

**Comment by frostworx** [comment]
Thanks for helping here @Erdragh 
yeah, @ranisalt please open a new issue and don't forget the logs.
please make sure to have read the corresponding wiki entries before - it might be written badly but covers a lot anyway already.
